# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-01-30 15:20
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='\u6807\u9898')),
                ('content', DjangoUeditor.models.UEditorField(max_length=100000, verbose_name='\u5185\u5bb9')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('isPublic', models.BooleanField(default=True, verbose_name='\u662f\u5426\u53d1\u5e03')),
                ('article_type', models.IntegerField(choices=[(0, '\u9875\u9762\u5185\u5bb9'), (1, '\u7814\u7a76\u8d44\u8baf'), (2, '\u91d1\u878d\u77e5\u8bc6')], default=1, verbose_name='\u6587\u7ae0\u7c7b\u578b')),
                ('author', models.CharField(max_length=10, verbose_name='\u4f5c\u8005')),
            ],
            options={
                'verbose_name': '\u6587\u7ae0',
                'verbose_name_plural': '\u6587\u7ae0',
            },
        ),
    ]
