# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-02-01 03:03
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_contactinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee_content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='\u6807\u9898')),
                ('content', DjangoUeditor.models.UEditorField(max_length=100000, verbose_name='\u5185\u5bb9')),
            ],
            options={
                'verbose_name': '\u4ecb\u7ecd\u9875\u9762',
                'verbose_name_plural': '\u4ecb\u7ecd\u9875\u9762',
            },
        ),
        migrations.CreateModel(
            name='Introduce_content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='\u6807\u9898')),
                ('content', DjangoUeditor.models.UEditorField(max_length=100000, verbose_name='\u5185\u5bb9')),
            ],
            options={
                'verbose_name': '\u4ecb\u7ecd\u9875\u9762',
                'verbose_name_plural': '\u4ecb\u7ecd\u9875\u9762',
            },
        ),
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name': '\u8054\u7cfb\u4eba\u4fe1\u606f', 'verbose_name_plural': '\u8054\u7cfb\u4eba\u4fe1\u606f'},
        ),
    ]
