# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-02-01 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20180201_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Join_form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u59d3\u540d')),
                ('aim', models.IntegerField(choices=[(1, '\u4e1a\u52a1\u529e\u7406'), (2, '\u6d3b\u52a8\u62a5\u540d'), (3, '\u5176\u4ed6'), (4, '\u8def\u8fc7\uff0c\u60f3\u4e86\u89e3\u4e00\u4e0b')], verbose_name='\u76ee\u7684')),
                ('phone', models.CharField(max_length=11, verbose_name='\u7535\u8bdd')),
                ('others', models.CharField(max_length=50000, verbose_name='\u5176\u4ed6')),
                ('isRead', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5df2\u8bfb')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u52a0\u5165\u6211\u4eec\u63d0\u4ea4\u5185\u5bb9',
                'verbose_name_plural': '\u52a0\u5165\u6211\u4eec\u63d0\u4ea4\u5185\u5bb9',
            },
        ),
        migrations.CreateModel(
            name='Key_word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u5173\u952e\u8bcd')),
            ],
            options={
                'verbose_name': '\u5173\u952e\u8bcd',
                'verbose_name_plural': '\u5173\u952e\u8bcd',
            },
        ),
        migrations.AlterModelOptions(
            name='fee_content',
            options={'verbose_name': '\u6536\u8d39\u9875\u9762', 'verbose_name_plural': '\u6536\u8d39\u9875\u9762'},
        ),
        migrations.AddField(
            model_name='article',
            name='keyword',
            field=models.ManyToManyField(to='index.Key_word'),
        ),
    ]
