# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-02-07 00:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20180206_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee_Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u5173\u952e\u8bcd')),
            ],
            options={
                'verbose_name': '\u8d39\u7387\u5173\u952e\u8bcd',
                'verbose_name_plural': '\u8d39\u7387\u5173\u952e\u8bcd',
            },
        ),
        migrations.CreateModel(
            name='Introduce_Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u5173\u952e\u8bcd')),
            ],
            options={
                'verbose_name': '\u4e1a\u52a1\u4fe1\u606f\u5173\u952e\u8bcd',
                'verbose_name_plural': '\u4e1a\u52a1\u4fe1\u606f\u5173\u952e\u8bcd',
            },
        ),
        migrations.CreateModel(
            name='MainPage_article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=b'', verbose_name='\u56fe\u7247')),
            ],
            options={
                'verbose_name': '\u9996\u9875\u5934\u56fe\u7ba1\u7406',
                'verbose_name_plural': '\u9996\u9875\u5934\u56fe\u7ba1\u7406',
            },
        ),
        migrations.AlterModelOptions(
            name='fee_content',
            options={'verbose_name': '\u8d39\u7387\u9875\u9762', 'verbose_name_plural': '\u8d39\u7387\u9875\u9762'},
        ),
        migrations.AlterModelOptions(
            name='introduce_content',
            options={'verbose_name': '\u4e1a\u52a1\u4fe1\u606f\u9875\u9762\u5185\u5bb9', 'verbose_name_plural': '\u4e1a\u52a1\u4fe1\u606f\u9875\u9762\u5185\u5bb9'},
        ),
        migrations.AddField(
            model_name='article',
            name='isHithLight',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u4e3a\u8981\u95fb'),
        ),
        migrations.AddField(
            model_name='mainpage_article',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Article'),
        ),
        migrations.AddField(
            model_name='fee_content',
            name='keyword',
            field=models.ManyToManyField(to='index.Fee_Keyword'),
        ),
        migrations.AddField(
            model_name='introduce_content',
            name='keyword',
            field=models.ManyToManyField(to='index.Introduce_Keyword'),
        ),
    ]
