# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-02-07 07:28
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20180207_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinpage_detail',
            name='bottomInfo',
            field=DjangoUeditor.models.UEditorField(max_length=50000, null=True, verbose_name='\u5e95\u90e8\u4fe1\u606f'),
        ),
        migrations.AlterField(
            model_name='joinpage_detail',
            name='topInfo',
            field=DjangoUeditor.models.UEditorField(max_length=50000, null=True, verbose_name='\u9876\u90e8\u4fe1\u606f'),
        ),
    ]
