# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-02-08 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_auto_20180207_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend_link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_name', models.CharField(max_length=100, verbose_name='\u53cb\u94fe\u540d')),
                ('link_url', models.URLField(verbose_name='\u94fe\u63a5')),
                ('isShow', models.BooleanField(default=True, verbose_name='\u662f\u5426\u5c55\u793a')),
            ],
            options={
                'verbose_name': '\u53cb\u60c5\u94fe\u63a5\u7ba1\u7406',
                'verbose_name_plural': '\u53cb\u60c5\u94fe\u63a5\u7ba1\u7406',
            },
        ),
    ]
