# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-02-10 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_auto_20180208_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Img_all',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u56fe\u7247\u540d')),
                ('img_url', models.ImageField(upload_to=b'', verbose_name='\u56fe\u7247')),
                ('link', models.URLField(verbose_name='\u5bf9\u5e94\u94fe\u63a5')),
            ],
            options={
                'verbose_name': '\u6240\u6709\u56fe\u7247',
                'verbose_name_plural': '\u6240\u6709\u56fe\u7247',
            },
        ),
        migrations.CreateModel(
            name='Index_img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=100, verbose_name='\u56fe\u7247\u4f4d\u7f6e')),
                ('img', models.ManyToManyField(to='index.Img_all')),
            ],
            options={
                'verbose_name': '\u9996\u9875\u56fe',
                'verbose_name_plural': '\u9996\u9875\u56fe',
            },
        ),
    ]
