# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-02-10 02:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_img_all_index_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainpage_article',
            options={'verbose_name': '\u9996\u9875\u6587\u7ae0\u5185\u5bb9', 'verbose_name_plural': '\u9996\u9875\u6587\u7ae0\u5185\u5bb9'},
        ),
        migrations.RemoveField(
            model_name='mainpage_article',
            name='image',
        ),
    ]
